name = "redirect-capture-poc"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-01-01"

compatibility_flags = ["nodejs_compat"]
version_metadata = { binding = "CF_VERSION_METADATA" }

[assets]
binding = "assets"
directory = ".svelte-kit/cloudflare"

[observability]
enabled = true
head_sampling_rate = 1